name: Auto Photo List

on:
  push:
    paths:
      - 'photos/**'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Create JSON
        run: |
          echo "{" > photos.json

          find photos -type f \( -iname "*.jpg" -o -iname "*.png" \) | while read file; do
            dir=$(dirname "$file" | sed 's|photos/||')
            name=$(basename "$file")
            echo "$dir|$name"
          done | sort | awk -F'|' '
          {
            if ($1 != prev) {
              if (NR != 1) print "],"
              printf "\"%s\": [", $1
              prev=$1
            } else {
              printf ","
            }
            printf "\"%s\"", $2
          }
          END {
            print "]"
          }' >> photos.json

          echo "}" >> photos.json

      - name: Commit JSON
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add photos.json
          git commit -m "auto update photos.json" || echo "no change"
          git push
